# This file is generated by gyp; do not edit.

include $(CLEAR_VARS)

LOCAL_MODULE_CLASS := GYP
LOCAL_MODULE := third_party_icu_icuuc_gyp
LOCAL_MODULE_STEM := icuuc
LOCAL_MODULE_SUFFIX := .stamp
LOCAL_MODULE_TAGS := optional
gyp_intermediate_dir := $(call local-intermediates-dir)
gyp_shared_intermediate_dir := $(call intermediates-dir-for,GYP,shared)

# Make sure our deps are built first.
GYP_TARGET_DEPENDENCIES := \
	$(call intermediates-dir-for,GYP,third_party_icu_system_icu_gyp)/system_icu.stamp

### Rules for action "generate_icuuc_shim_headers":
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h: gyp_local_path := $(LOCAL_PATH)
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h: gyp_intermediate_dir := $(abspath $(gyp_intermediate_dir))
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h: gyp_shared_intermediate_dir := $(abspath $(gyp_shared_intermediate_dir))
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h: export PATH := $(subst $(ANDROID_BUILD_PATHS),,$(PATH))
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h: $(LOCAL_PATH)/tools/generate_shim_headers/generate_shim_headers.py $(GYP_TARGET_DEPENDENCIES)
	@echo "Gyp action: Generating icuuc shim headers. ($@)"
	$(hide)cd $(gyp_local_path)/third_party/icu; mkdir -p $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode; python ../../tools/generate_shim_headers/generate_shim_headers.py --headers-root public/common --output-directory "$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target" unicode/brkiter.h unicode/bytestream.h unicode/caniter.h unicode/chariter.h unicode/dbbi.h unicode/docmain.h unicode/dtintrv.h unicode/errorcode.h unicode/icudataver.h unicode/icuplug.h unicode/idna.h unicode/localpointer.h unicode/locid.h unicode/normalizer2.h unicode/normlzr.h unicode/pandroid.h unicode/parseerr.h unicode/parsepos.h unicode/pfreebsd.h unicode/plinux.h unicode/pmac.h unicode/popenbsd.h unicode/ppalmos.h unicode/ptypes.h unicode/putil.h unicode/pwin32.h unicode/rbbi.h unicode/rep.h unicode/resbund.h unicode/schriter.h unicode/std_string.h unicode/strenum.h unicode/stringpiece.h unicode/symtable.h unicode/ubidi.h unicode/ubrk.h unicode/ucasemap.h unicode/ucat.h unicode/uchar.h unicode/uchriter.h unicode/uclean.h unicode/ucnv_cb.h unicode/ucnv_err.h unicode/ucnv.h unicode/ucnvsel.h unicode/uconfig.h unicode/udata.h unicode/udeprctd.h unicode/udraft.h unicode/uenum.h unicode/uidna.h unicode/uintrnal.h unicode/uiter.h unicode/uloc.h unicode/umachine.h unicode/umisc.h unicode/unifilt.h unicode/unifunct.h unicode/unimatch.h unicode/uniset.h unicode/unistr.h unicode/unorm2.h unicode/unorm.h unicode/uobject.h unicode/uobslete.h unicode/urename.h unicode/urep.h unicode/ures.h unicode/uscript.h unicode/uset.h unicode/usetiter.h unicode/ushape.h unicode/usprep.h unicode/ustring.h unicode/usystem.h unicode/utext.h unicode/utf16.h unicode/utf32.h unicode/utf8.h unicode/utf.h unicode/utf_old.h unicode/utrace.h unicode/utypeinfo.h unicode/utypes.h unicode/uvernum.h unicode/uversion.h --generate

$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/bytestream.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/caniter.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/chariter.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/dbbi.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/docmain.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/dtintrv.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/errorcode.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/icudataver.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/icuplug.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/idna.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/localpointer.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/locid.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/normalizer2.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/normlzr.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/pandroid.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/parseerr.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/parsepos.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/pfreebsd.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/plinux.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/pmac.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/popenbsd.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/ppalmos.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/ptypes.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/putil.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/pwin32.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/rbbi.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/rep.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/resbund.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/schriter.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/std_string.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/strenum.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/stringpiece.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/symtable.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/ubidi.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/ubrk.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/ucasemap.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/ucat.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/uchar.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/uchriter.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/uclean.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/ucnv_cb.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/ucnv_err.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/ucnv.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/ucnvsel.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/uconfig.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/udata.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/udeprctd.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/udraft.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/uenum.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/uidna.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/uintrnal.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/uiter.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/uloc.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/umachine.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/umisc.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/unifilt.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/unifunct.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/unimatch.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/uniset.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/unistr.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/unorm2.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/unorm.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/uobject.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/uobslete.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/urename.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/urep.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/ures.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/uscript.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/uset.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/usetiter.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/ushape.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/usprep.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/ustring.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/usystem.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/utext.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/utf16.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/utf32.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/utf8.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/utf.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/utf_old.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/utrace.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/utypeinfo.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/utypes.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/uvernum.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;
$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/uversion.h: $(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h ;


GYP_GENERATED_OUTPUTS := \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/brkiter.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/bytestream.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/caniter.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/chariter.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/dbbi.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/docmain.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/dtintrv.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/errorcode.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/icudataver.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/icuplug.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/idna.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/localpointer.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/locid.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/normalizer2.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/normlzr.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/pandroid.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/parseerr.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/parsepos.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/pfreebsd.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/plinux.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/pmac.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/popenbsd.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/ppalmos.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/ptypes.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/putil.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/pwin32.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/rbbi.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/rep.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/resbund.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/schriter.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/std_string.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/strenum.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/stringpiece.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/symtable.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/ubidi.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/ubrk.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/ucasemap.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/ucat.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/uchar.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/uchriter.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/uclean.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/ucnv_cb.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/ucnv_err.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/ucnv.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/ucnvsel.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/uconfig.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/udata.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/udeprctd.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/udraft.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/uenum.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/uidna.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/uintrnal.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/uiter.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/uloc.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/umachine.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/umisc.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/unifilt.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/unifunct.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/unimatch.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/uniset.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/unistr.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/unorm2.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/unorm.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/uobject.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/uobslete.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/urename.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/urep.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/ures.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/uscript.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/uset.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/usetiter.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/ushape.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/usprep.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/ustring.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/usystem.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/utext.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/utf16.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/utf32.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/utf8.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/utf.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/utf_old.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/utrace.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/utypeinfo.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/utypes.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/uvernum.h \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target/third_party/icu/public/common/unicode/uversion.h

# Make sure our deps and generated files are built first.
LOCAL_ADDITIONAL_DEPENDENCIES := $(GYP_TARGET_DEPENDENCIES) $(GYP_GENERATED_OUTPUTS)

### Rules for final target.
# Add target alias to "gyp_all_modules" target.
.PHONY: gyp_all_modules
gyp_all_modules: third_party_icu_icuuc_gyp

# Alias gyp target name.
.PHONY: icuuc
icuuc: third_party_icu_icuuc_gyp

LOCAL_MODULE_PATH := $(PRODUCT_OUT)/gyp_stamp
LOCAL_UNINSTALLABLE_MODULE := true

include $(BUILD_SYSTEM)/base_rules.mk

$(LOCAL_BUILT_MODULE): $(LOCAL_ADDITIONAL_DEPENDENCIES)
	$(hide) echo "Gyp timestamp: $@"
	$(hide) mkdir -p $(dir $@)
	$(hide) touch $@
